"""The curated English core pack: 30 lessons of 8 phrases, levels 1 to 4.

Why this exists: the app's fixed content was one three-phrase lesson per level,
so a student without an AI key (or with the day's credits spent) ran out of
material on the first afternoon. This pack is the floor the product stands on —
enough real English, written and checked by a person, that the app is useful
before a single provider call is made.

Shape of a lesson entry:

    slug      file name and stable identity of the lesson
    level     the student level it is shown at (1..4 here; A1 to A2)
    title     what the student sees
    theme     grouping, also used as the lesson's subject name
    objective one sentence about what the lesson is for
    items     8 tuples of (phrase_en, phrase_pt, example_en, example_pt)

`GLOSSARY` maps each word used in a *phrase* to its Portuguese meaning, which is
what builds the word-by-word breakdown the lesson screen shows. Keeping it in one
place is what keeps "my" translated the same way in all thirty lessons.

Run `python scripts/build_english_core_pack.py` after changing anything here.
"""

from __future__ import annotations

LESSONS: list[dict] = [
    # ── Level 1 · A1, the first words ─────────────────────────────────────────
    {
        "slug": "core_a1_01_greetings",
        "level": 1,
        "title": "Inglês A1 - Cumprimentos",
        "theme": "Cumprimentos",
        "objective": "Dizer oi, tchau e como você está.",
        "items": [
            ("Hello!", "Oi!", "Hello! Nice to see you.", "Oi! Que bom te ver."),
            ("Good morning", "Bom dia", "Good morning, teacher!", "Bom dia, professora!"),
            ("Good afternoon", "Boa tarde", "Good afternoon, everyone.", "Boa tarde, pessoal."),
            ("Good night", "Boa noite", "Good night, sleep well.", "Boa noite, durma bem."),
            ("How are you?", "Como você está?", "Hi Ana, how are you?", "Oi Ana, como você está?"),
            ("I am fine", "Eu estou bem", "I am fine, thank you.", "Eu estou bem, obrigado."),
            ("Nice to meet you", "Prazer em conhecer você", "Nice to meet you, Lucas.", "Prazer em conhecer você, Lucas."),
            ("Goodbye!", "Tchau!", "Goodbye! See you tomorrow.", "Tchau! Até amanhã."),
        ],
    },
    {
        "slug": "core_a1_02_about_me",
        "level": 1,
        "title": "Inglês A1 - Sobre mim",
        "theme": "Sobre mim",
        "objective": "Falar seu nome, sua idade e de onde você é.",
        "items": [
            ("My name is Ana", "Meu nome é Ana", "Hello, my name is Ana.", "Olá, meu nome é Ana."),
            ("What is your name?", "Qual é o seu nome?", "Hi! What is your name?", "Oi! Qual é o seu nome?"),
            ("I am twenty years old", "Eu tenho vinte anos", "She is thirty years old.", "Ela tem trinta anos."),
            ("How old are you?", "Quantos anos você tem?", "How old are you, Lucas?", "Quantos anos você tem, Lucas?"),
            ("I am from Brazil", "Eu sou do Brasil", "I am from Brazil, from Recife.", "Eu sou do Brasil, de Recife."),
            ("Where are you from?", "De onde você é?", "Where are you from, Mia?", "De onde você é, Mia?"),
            ("I speak Portuguese", "Eu falo português", "I speak Portuguese and English.", "Eu falo português e inglês."),
            ("This is my friend", "Este é o meu amigo", "This is my friend Pedro.", "Este é o meu amigo Pedro."),
        ],
    },
    {
        "slug": "core_a1_03_family",
        "level": 1,
        "title": "Inglês A1 - Família",
        "theme": "Família",
        "objective": "Falar das pessoas da sua família.",
        "items": [
            ("my mother", "minha mãe", "My mother cooks very well.", "Minha mãe cozinha muito bem."),
            ("my father", "meu pai", "My father works in the city.", "Meu pai trabalha na cidade."),
            ("my sister", "minha irmã", "My sister is six years old.", "Minha irmã tem seis anos."),
            ("my brother", "meu irmão", "My brother plays football.", "Meu irmão joga futebol."),
            ("my grandmother", "minha avó", "My grandmother tells good stories.", "Minha avó conta boas histórias."),
            ("my grandfather", "meu avô", "My grandfather has a garden.", "Meu avô tem um jardim."),
            ("I love my family", "Eu amo a minha família", "I love my family very much.", "Eu amo muito a minha família."),
            ("We are at home", "Nós estamos em casa", "We are at home today.", "Nós estamos em casa hoje."),
        ],
    },
    {
        "slug": "core_a1_04_numbers",
        "level": 1,
        "title": "Inglês A1 - Números",
        "theme": "Números",
        "objective": "Contar de um a dez e falar quantidades.",
        "items": [
            ("one, two, three", "um, dois, três", "Count with me: one, two, three.", "Conte comigo: um, dois, três."),
            ("four, five, six", "quatro, cinco, seis", "I have four, five, six pencils.", "Eu tenho quatro, cinco, seis lápis."),
            ("seven, eight, nine", "sete, oito, nove", "Seven, eight, nine birds are here.", "Sete, oito, nove pássaros estão aqui."),
            ("ten", "dez", "There are ten students here.", "Há dez estudantes aqui."),
            ("How many?", "Quantos?", "How many apples do you have?", "Quantas macas você tem?"),
            ("I have two dogs", "Eu tenho dois cachorros", "I have two dogs at home.", "Eu tenho dois cachorros em casa."),
            ("the first one", "o primeiro", "The first one is mine.", "O primeiro é meu."),
            ("many books", "muitos livros", "She reads many books.", "Ela lê muitos livros."),
        ],
    },
    {
        "slug": "core_a1_05_colours",
        "level": 1,
        "title": "Inglês A1 - Cores",
        "theme": "Cores",
        "objective": "Falar as cores das coisas ao seu redor.",
        "items": [
            ("red", "vermelho", "The apple is red.", "A maçã é vermelha."),
            ("blue", "azul", "The sky is blue today.", "O céu está azul hoje."),
            ("green", "verde", "The grass is green.", "A grama é verde."),
            ("yellow", "amarelo", "The sun looks yellow.", "O sol parece amarelo."),
            ("black", "preto", "My cat is black.", "Meu gato é preto."),
            ("white", "branco", "The paper is white.", "O papel é branco."),
            ("What colour is it?", "Que cor é?", "What colour is your bag?", "Que cor é a sua mochila?"),
            ("my favourite colour", "minha cor favorita", "Green is my favourite colour.", "Verde é a minha cor favorita."),
        ],
    },
    {
        "slug": "core_a1_06_animals",
        "level": 1,
        "title": "Inglês A1 - Animais",
        "theme": "Animais",
        "objective": "Nomear animais e dizer o que eles fazem.",
        "items": [
            ("a dog", "um cachorro", "A dog runs in the park.", "Um cachorro corre no parque."),
            ("a cat", "um gato", "A cat sleeps on the sofa.", "Um gato dorme no sofa."),
            ("a bird", "um passaro", "A bird sings in the tree.", "Um passaro canta na arvore."),
            ("a fish", "um peixe", "A fish swims in the water.", "Um peixe nada na água."),
            ("a horse", "um cavalo", "A horse eats grass.", "Um cavalo come grama."),
            ("a rabbit", "um coelho", "A rabbit jumps very fast.", "Um coelho pula muito rápido."),
            ("I like animals", "Eu gosto de animais", "I like animals, especially cats.", "Eu gosto de animais, especialmente gatos."),
            ("the animals eat", "os animais comem", "The animals eat in the morning.", "Os animais comem de manhã."),
        ],
    },
    {
        "slug": "core_a1_07_food",
        "level": 1,
        "title": "Inglês A1 - Comida",
        "theme": "Comida",
        "objective": "Falar de comida e bebida do dia a dia.",
        "items": [
            ("bread", "pão", "I eat bread for breakfast.", "Eu como pão no café da manhã."),
            ("milk", "leite", "She drinks milk every morning.", "Ela bebe leite toda manhã."),
            ("water", "água", "Please give me water.", "Por favor me de água."),
            ("an apple", "uma maçã", "An apple is a good snack.", "Uma maçã é um bom lanche."),
            ("rice and beans", "arroz e feijão", "We eat rice and beans at lunch.", "Nos comemos arroz e feijão no almoço."),
            ("I am hungry", "Eu estou com fome", "I am hungry, let us eat.", "Eu estou com fome, vamos comer."),
            ("I am thirsty", "Eu estou com sede", "I am thirsty after the game.", "Eu estou com sede depois do jogo."),
            ("It is delicious", "Está delicioso", "This cake is delicious.", "Este bolo está delicioso."),
        ],
    },
    {
        "slug": "core_a1_08_school",
        "level": 1,
        "title": "Inglês A1 - Estudar",
        "theme": "Estudos",
        "objective": "Falar das coisas e das pessoas do seu lugar de estudo.",
        "items": [
            ("my school", "minha escola", "My school is near my house.", "Minha escola é perto da minha casa."),
            ("my teacher", "meu professor", "My teacher is very kind.", "Meu professor é muito gentil."),
            ("a book", "um livro", "I read a book every night.", "Eu leio um livro toda noite."),
            ("a pencil", "um lápis", "I write with a pencil.", "Eu escrevo com um lápis."),
            ("my backpack", "minha mochila", "My backpack is heavy today.", "Minha mochila está pesada hoje."),
            ("the classroom", "a sala de aula", "The classroom is big and bright.", "A sala de aula é grande e clara."),
            ("I study every day", "Eu estudo todo dia", "I study every day after school.", "Eu estudo todo dia depois da escola."),
            ("I have a question", "Eu tenho uma pergunta", "I have a question about this word.", "Eu tenho uma pergunta sobre esta palavra."),
        ],
    },
    # ── Level 2 · A1, the everyday world ──────────────────────────────────────
    {
        "slug": "core_a1_09_feelings",
        "level": 2,
        "title": "Inglês A1 - Sentimentos",
        "theme": "Sentimentos",
        "objective": "Dizer como você se sente hoje.",
        "items": [
            ("I am happy", "Eu estou feliz", "I am happy to see you.", "Eu estou feliz em te ver."),
            ("I am sad", "Eu estou triste", "I am sad because it is raining.", "Eu estou triste porque está chovendo."),
            ("I am tired", "Eu estou cansado", "I am tired after the game.", "Eu estou cansado depois do jogo."),
            ("I am afraid", "Eu estou com medo", "I am afraid of the dark.", "Eu estou com medo do escuro."),
            ("I am excited", "Eu estou animado", "I am excited about the trip.", "Eu estou animado com a viagem."),
            ("Are you okay?", "Você está bem?", "Are you okay, my friend?", "Você está bem, meu amigo?"),
            ("Do not worry", "Não se preocupe", "Do not worry, I am here.", "Não se preocupe, eu estou aqui."),
            ("I feel better now", "Eu me sinto melhor agora", "I feel better now, thank you.", "Eu me sinto melhor agora, obrigado."),
        ],
    },
    {
        "slug": "core_a1_10_body",
        "level": 2,
        "title": "Inglês A1 - O corpo",
        "theme": "Corpo",
        "objective": "Nomear partes do corpo.",
        "items": [
            ("my head", "minha cabeça", "My head hurts a little.", "Minha cabeça dói um pouco."),
            ("my hand", "minha mão", "I write with my hand.", "Eu escrevo com a minha mão."),
            ("my foot", "meu pé", "My foot is in the water.", "Meu pé está na água."),
            ("my eyes", "meus olhos", "My eyes are brown.", "Meus olhos são castanhos."),
            ("my hair", "meu cabelo", "My hair is long and black.", "Meu cabelo é longo e preto."),
            ("my mouth", "minha boca", "I open my mouth to speak.", "Eu abro a boca para falar."),
            ("Wash your hands", "Lave as mãos", "Wash your hands before lunch.", "Lave as mãos antes do almoço."),
            ("Look at me", "Olhe para mim", "Look at me, please.", "Olhe para mim, por favor."),
        ],
    },
    {
        "slug": "core_a1_11_clothes",
        "level": 2,
        "title": "Inglês A1 - Roupas",
        "theme": "Roupas",
        "objective": "Falar do que você está vestindo.",
        "items": [
            ("a shirt", "uma camisa", "He wears a blue shirt.", "Ele usa uma camisa azul."),
            ("trousers", "calça", "These trousers are new.", "Esta calça é nova."),
            ("shoes", "sapatos", "My shoes are dirty.", "Meus sapatos estão sujos."),
            ("a jacket", "uma jaqueta", "Take a jacket, it is cold.", "Leve uma jaqueta, está frio."),
            ("a hat", "um chapéu", "She wears a hat in the sun.", "Ela usa um chapéu no sol."),
            ("I am wearing a dress", "Eu estou usando um vestido", "I am wearing a red dress.", "Eu estou usando um vestido vermelho."),
            ("Put on your shoes", "Calce os sapatos", "Put on your shoes, we are late.", "Calce os sapatos, estamos atrasados."),
            ("It is too big", "Está grande demais", "This shirt is too big for me.", "Esta camisa está grande demais para mim."),
        ],
    },
    {
        "slug": "core_a1_12_house",
        "level": 2,
        "title": "Inglês A1 - Em casa",
        "theme": "Casa",
        "objective": "Falar dos cômodos e das coisas de casa.",
        "items": [
            ("my house", "minha casa", "My house has a small garden.", "Minha casa tem um jardim pequeno."),
            ("the kitchen", "a cozinha", "We cook in the kitchen.", "Nos cozinhamos na cozinha."),
            ("my bedroom", "meu quarto", "My bedroom is upstairs.", "Meu quarto fica em cima."),
            ("the bathroom", "o banheiro", "The bathroom is on the left.", "O banheiro fica à esquerda."),
            ("a table", "uma mesa", "We eat at the table.", "Nos comemos a mesa."),
            ("a bed", "uma cama", "My bed is very soft.", "Minha cama é bem macia."),
            ("Come in, please", "Entre, por favor", "Come in, please, it is open.", "Entre, por favor, está aberto."),
            ("Close the door", "Feche a porta", "Close the door, it is cold.", "Feche a porta, está frio."),
        ],
    },
    {
        "slug": "core_a1_13_play",
        "level": 2,
        "title": "Inglês A1 - Jogos e lazer",
        "theme": "Jogos e lazer",
        "objective": "Falar de jogos e tempo livre.",
        "items": [
            ("Let us play", "Vamos jogar", "Let us play a game after lunch.", "Vamos jogar depois do almoço."),
            ("a ball", "uma bola", "Throw me the ball, please.", "Jogue a bola para mim, por favor."),
            ("a game", "um jogo", "This game is really fun.", "Este jogo é bem divertido."),
            ("my turn", "minha vez", "It is my turn now.", "Agora é a minha vez."),
            ("your turn", "sua vez", "It is your turn, go ahead.", "É a sua vez, pode ir."),
            ("I won!", "Eu ganhei!", "I won the game!", "Eu ganhei o jogo!"),
            ("Let us try again", "Vamos tentar de novo", "Let us try again tomorrow.", "Vamos tentar de novo amanhã."),
            ("That is fun", "Isso é divertido", "Riding a bike is fun.", "Andar de bicicleta é divertido."),
        ],
    },
    {
        "slug": "core_a1_14_time_weather",
        "level": 2,
        "title": "Inglês A1 - Dias e tempo",
        "theme": "Dias e tempo",
        "objective": "Falar dos dias da semana e do tempo.",
        "items": [
            ("today", "hoje", "Today is a good day.", "Hoje é um bom dia."),
            ("tomorrow", "amanhã", "Tomorrow we go to school.", "Amanhã nós vamos para a escola."),
            ("yesterday", "ontem", "Yesterday was very hot.", "Ontem estava muito quente."),
            ("on Monday", "na segunda-feira", "On Monday I have English.", "Na segunda-feira eu tenho inglês."),
            ("It is sunny", "Está ensolarado", "It is sunny, let us go out.", "Está ensolarado, vamos sair."),
            ("It is raining", "Está chovendo", "It is raining a lot today.", "Está chovendo muito hoje."),
            ("It is cold", "Está frio", "It is cold in the morning.", "Está frio de manhã."),
            ("What time is it?", "Que horas são?", "What time is it, please?", "Que horas são, por favor?"),
        ],
    },
    {
        "slug": "core_a1_15_polite",
        "level": 2,
        "title": "Inglês A1 - Pedir com educação",
        "theme": "Pedidos",
        "objective": "Pedir as coisas com educação.",
        "items": [
            ("please", "por favor", "Can you help me, please?", "Você pode me ajudar, por favor?"),
            ("thank you", "obrigado", "Thank you for your help.", "Obrigado pela sua ajuda."),
            ("You are welcome", "De nada", "You are welcome, my friend.", "De nada, meu amigo."),
            ("I am sorry", "Me desculpe", "I am sorry, it was my mistake.", "Me desculpe, foi erro meu."),
            ("Excuse me", "Com licença", "Excuse me, where is the door?", "Com licença, onde fica a porta?"),
            ("Can I help you?", "Posso ajudar?", "Can I help you with that?", "Posso ajudar com isso?"),
            ("May I have water?", "Posso pegar água?", "May I have water, please?", "Posso pegar água, por favor?"),
            ("Of course", "Claro", "Of course, take it.", "Claro, pode pegar."),
        ],
    },
    {
        "slug": "core_a1_16_questions",
        "level": 2,
        "title": "Inglês A1 - Perguntas simples",
        "theme": "Perguntas",
        "objective": "Fazer perguntas básicas com what, where e who.",
        "items": [
            ("What is this?", "O que é isto?", "What is this in English?", "O que é isto em inglês?"),
            ("Where is it?", "Onde está?", "Where is my pencil?", "Onde está o meu lápis?"),
            ("Who is that?", "Quem é aquele?", "Who is that boy over there?", "Quem é aquele menino ali?"),
            ("Why not?", "Por que não?", "Why not try again?", "Por que não tentar de novo?"),
            ("When is the class?", "Quando é a aula?", "When is the English class?", "Quando é a aula de inglês?"),
            ("How do you say it?", "Como se diz?", "How do you say it in Portuguese?", "Como se diz isso em português?"),
            ("Can you repeat?", "Você pode repetir?", "Can you repeat that, please?", "Você pode repetir isso, por favor?"),
            ("I do not know", "Eu não sei", "I do not know the answer.", "Eu não sei a resposta."),
        ],
    },
    # ── Level 3 · A2, routine and opinion ─────────────────────────────────────
    {
        "slug": "core_a2_17_routine",
        "level": 3,
        "title": "Inglês A2 - Rotina",
        "theme": "Rotina",
        "objective": "Contar o que você faz todos os dias.",
        "items": [
            ("I wake up early", "Eu acordo cedo", "I wake up early every day.", "Eu acordo cedo todo dia."),
            ("I brush my teeth", "Eu escovo os dentes", "I brush my teeth after breakfast.", "Eu escovo os dentes depois do café."),
            ("I go to school", "Eu vou para a escola", "I go to school at seven.", "Eu vou para a escola as sete."),
            ("I do my homework", "Eu faço a minha lição", "I do my homework in the afternoon.", "Eu faço a minha lição à tarde."),
            ("I help at home", "Eu ajudo em casa", "I help at home on Saturdays.", "Eu ajudo em casa aos sábados."),
            ("I go to bed at nine", "Eu vou dormir às nove", "I go to bed at nine o'clock.", "Eu vou dormir às nove horas."),
            ("every morning", "toda manhã", "Every morning I drink milk.", "Toda manhã eu bebo leite."),
            ("after lunch", "depois do almoço", "After lunch I read a book.", "Depois do almoço eu leio um livro."),
        ],
    },
    {
        "slug": "core_a2_18_verbs",
        "level": 3,
        "title": "Inglês A2 - Verbos do dia a dia",
        "theme": "Verbos",
        "objective": "Usar verbos comuns no presente.",
        "items": [
            ("I eat", "Eu como", "I eat fruit every day.", "Eu como fruta todo dia."),
            ("She works", "Ela trabalha", "She works at a hospital.", "Ela trabalha em um hospital."),
            ("He studies", "Ele estuda", "He studies English at night.", "Ele estuda inglês à noite."),
            ("We live here", "Nos moramos aqui", "We live here with our dog.", "Nos moramos aqui com o nosso cachorro."),
            ("They play", "Eles jogam", "They play in the park.", "Eles jogam no parque."),
            ("I do not like it", "Eu não gosto disso", "I do not like cold soup.", "Eu não gosto de sopa fria."),
            ("Does she know?", "Ela sabe?", "Does she know the answer?", "Ela sabe a resposta?"),
            ("He never forgets", "Ele nunca esquece", "He never forgets my birthday.", "Ele nunca esquece o meu aniversario."),
        ],
    },
    {
        "slug": "core_a2_19_likes",
        "level": 3,
        "title": "Inglês A2 - Gostos",
        "theme": "Gostos",
        "objective": "Dizer do que você gosta e do que não gosta.",
        "items": [
            ("I like music", "Eu gosto de música", "I like music from Brazil.", "Eu gosto de música do Brasil."),
            ("I love reading", "Eu amo ler", "I love reading before bed.", "Eu amo ler antes de dormir."),
            ("I do not like waiting", "Eu não gosto de esperar", "I do not like waiting in line.", "Eu não gosto de esperar na fila."),
            ("My favourite food", "Minha comida favorita", "My favourite food is pizza.", "Minha comida favorita é pizza."),
            ("I prefer tea", "Eu prefiro chá", "I prefer tea to coffee.", "Eu prefiro chá a café."),
            ("What do you think?", "O que você acha?", "What do you think about this song?", "O que você acha desta música?"),
            ("I agree with you", "Eu concordo com você", "I agree with you about the film.", "Eu concordo com você sobre o filme."),
            ("It depends", "Depende", "It depends on the weather.", "Depende do tempo."),
        ],
    },
    {
        "slug": "core_a2_20_places",
        "level": 3,
        "title": "Inglês A2 - Lugares",
        "theme": "Lugares",
        "objective": "Falar de lugares da cidade e como chegar.",
        "items": [
            ("the park", "o parque", "The park is next to my house.", "O parque fica ao lado da minha casa."),
            ("the market", "o mercado", "We buy fruit at the market.", "Nos compramos fruta no mercado."),
            ("the hospital", "o hospital", "The hospital is far from here.", "O hospital fica longe daqui."),
            ("the bus stop", "o ponto de ônibus", "I wait at the bus stop.", "Eu espero no ponto de ônibus."),
            ("Turn left", "Vire à esquerda", "Turn left at the corner.", "Vire à esquerda na esquina."),
            ("Go straight ahead", "Siga em frente", "Go straight ahead for two streets.", "Siga em frente por duas ruas."),
            ("It is near here", "É perto daqui", "The school is near here.", "A escola é perto daqui."),
            ("How do I get there?", "Como eu chego lá?", "How do I get there by bus?", "Como eu chego lá de ônibus?"),
        ],
    },
    {
        "slug": "core_a2_21_shopping",
        "level": 3,
        "title": "Inglês A2 - Compras",
        "theme": "Compras",
        "objective": "Comprar coisas e perguntar o preço.",
        "items": [
            ("How much is it?", "Quanto custa?", "How much is this book?", "Quanto custa este livro?"),
            ("It is expensive", "Está caro", "This jacket is expensive.", "Esta jaqueta está cara."),
            ("It is cheap", "Está barato", "The bread is cheap here.", "O pão é barato aqui."),
            ("I would like this one", "Eu queria este", "I would like this one, please.", "Eu queria este, por favor."),
            ("Do you have a bigger size?", "Você tem um tamanho maior?", "Do you have a bigger size, please?", "Você tem um tamanho maior, por favor?"),
            ("I am just looking", "Eu só estou olhando", "Thank you, I am just looking.", "Obrigado, eu só estou olhando."),
            ("Can I pay by card?", "Posso pagar com cartão?", "Can I pay by card here?", "Posso pagar com cartão aqui?"),
            ("Here is your change", "Aqui está o seu troco", "Here is your change, thank you.", "Aqui está o seu troco, obrigado."),
        ],
    },
    {
        "slug": "core_a2_22_travel",
        "level": 3,
        "title": "Inglês A2 - Viagem",
        "theme": "Viagem",
        "objective": "Falar de viagens e transporte.",
        "items": [
            ("a trip", "uma viagem", "We are planning a trip.", "Nós estamos planejando uma viagem."),
            ("by bus", "de ônibus", "I go to school by bus.", "Eu vou para a escola de ônibus."),
            ("by plane", "de avião", "They travel by plane.", "Eles viajam de avião."),
            ("a ticket", "uma passagem", "I need a ticket to Rio.", "Eu preciso de uma passagem para o Rio."),
            ("Where is the station?", "Onde fica a estação?", "Excuse me, where is the station?", "Com licença, onde fica a estação?"),
            ("I am lost", "Eu estou perdido", "I am lost, can you help me?", "Eu estou perdido, você pode me ajudar?"),
            ("It takes two hours", "Leva duas horas", "The trip takes two hours.", "A viagem leva duas horas."),
            ("Have a good trip", "Boa viagem", "Have a good trip, see you soon.", "Boa viagem, até logo."),
        ],
    },
    {
        "slug": "core_a2_23_now",
        "level": 3,
        "title": "Inglês A2 - Agora mesmo",
        "theme": "Presente contínuo",
        "objective": "Dizer o que está acontecendo agora.",
        "items": [
            ("I am reading", "Eu estou lendo", "I am reading a funny book.", "Eu estou lendo um livro engraçado."),
            ("She is cooking", "Ela está cozinhando", "She is cooking dinner now.", "Ela está cozinhando o jantar agora."),
            ("They are playing", "Eles estão jogando", "They are playing outside.", "Eles estão jogando lá fora."),
            ("We are studying", "Nós estamos estudando", "We are studying for the test.", "Nós estamos estudando para a prova."),
            ("What are you doing?", "O que você está fazendo?", "What are you doing right now?", "O que você está fazendo agora?"),
            ("I am not sleeping", "Eu não estou dormindo", "I am not sleeping, I am thinking.", "Eu não estou dormindo, eu estou pensando."),
            ("right now", "agora mesmo", "I am busy right now.", "Eu estou ocupado agora mesmo."),
            ("at the moment", "no momento", "He is away at the moment.", "Ele está fora no momento."),
        ],
    },
    # ── Level 4 · A2, telling a story ─────────────────────────────────────────
    {
        "slug": "core_a2_24_past",
        "level": 4,
        "title": "Inglês A2 - Ontem",
        "theme": "Passado",
        "objective": "Contar o que aconteceu no passado.",
        "items": [
            ("I played", "Eu joguei", "I played football yesterday.", "Eu joguei futebol ontem."),
            ("She went out", "Ela saiu", "She went out with her friends.", "Ela saiu com as amigas."),
            ("We watched a film", "Nós assistimos a um filme", "We watched a film last night.", "Nós assistimos a um filme ontem à noite."),
            ("He did not come", "Ele não veio", "He did not come to the party.", "Ele não veio à festa."),
            ("Did you see it?", "Você viu?", "Did you see the game?", "Você viu o jogo?"),
            ("last week", "semana passada", "I was sick last week.", "Eu estava doente semana passada."),
            ("two days ago", "dois dias atrás", "She called me two days ago.", "Ela me ligou dois dias atrás."),
            ("It was great", "Foi ótimo", "The trip was great.", "A viagem foi ótima."),
        ],
    },
    {
        "slug": "core_a2_25_plans",
        "level": 4,
        "title": "Inglês A2 - Planos",
        "theme": "Planos",
        "objective": "Falar de planos e do futuro.",
        "items": [
            ("I am going to study", "Eu vou estudar", "I am going to study tonight.", "Eu vou estudar hoje à noite."),
            ("We will travel", "Nos vamos viajar", "We will travel in July.", "Nos vamos viajar em julho."),
            ("Next weekend", "No próximo fim de semana", "Next weekend we visit grandma.", "No próximo fim de semana nós visitamos a vovó."),
            ("What are your plans?", "Quais são os seus planos?", "What are your plans for today?", "Quais são os seus planos para hoje?"),
            ("Maybe later", "Talvez mais tarde", "Maybe later we can play.", "Talvez mais tarde a gente possa brincar."),
            ("I hope so", "Eu espero que sim", "Will it be sunny? I hope so.", "Vai fazer sol? Eu espero que sim."),
            ("I promise", "Eu prometo", "I promise I will help you.", "Eu prometo que vou te ajudar."),
            ("See you soon", "Até logo", "See you soon, take care.", "Até logo, se cuida."),
        ],
    },
    {
        "slug": "core_a2_26_compare",
        "level": 4,
        "title": "Inglês A2 - Comparar",
        "theme": "Comparacoes",
        "objective": "Comparar coisas e pessoas.",
        "items": [
            ("bigger than", "maior que", "My dog is bigger than yours.", "Meu cachorro é maior que o seu."),
            ("smaller than", "menor que", "This box is smaller than that one.", "Esta caixa é menor que aquela."),
            ("better than", "melhor que", "This book is better than the film.", "Este livro é melhor que o filme."),
            ("the best", "o melhor", "She is the best in the class.", "Ela é a melhor da turma."),
            ("the same", "o mesmo", "We have the same bag.", "Nos temos a mesma mochila."),
            ("as fast as", "tão rápido quanto", "He runs as fast as me.", "Ele corre tão rápido quanto eu."),
            ("more difficult", "mais difícil", "This exercise is more difficult.", "Este exercício é mais difícil."),
            ("less noisy", "menos barulhento", "The new room is less noisy.", "A sala nova é menos barulhenta."),
        ],
    },
    {
        "slug": "core_a2_27_health",
        "level": 4,
        "title": "Inglês A2 - Saúde",
        "theme": "Saúde",
        "objective": "Dizer o que está doendo e pedir ajuda.",
        "items": [
            ("I do not feel well", "Eu não estou me sentindo bem", "I do not feel well today.", "Eu não estou me sentindo bem hoje."),
            ("My throat hurts", "Minha garganta dói", "My throat hurts since yesterday.", "Minha garganta dói desde ontem."),
            ("I have a fever", "Eu estou com febre", "I have a fever and a cough.", "Eu estou com febre e tosse."),
            ("Call the doctor", "Chame o médico", "Call the doctor, please.", "Chame o médico, por favor."),
            ("Take this medicine", "Tome este remédio", "Take this medicine after lunch.", "Tome este remédio depois do almoço."),
            ("Get well soon", "Melhoras", "Get well soon, my friend.", "Melhoras, meu amigo."),
            ("Be careful", "Tenha cuidado", "Be careful with the stairs.", "Tenha cuidado com a escada."),
            ("It is an emergency", "É uma emergência", "Help, it is an emergency!", "Socorro, é uma emergência!"),
        ],
    },
    {
        "slug": "core_a2_28_invite",
        "level": 4,
        "title": "Inglês A2 - Convites",
        "theme": "Convites",
        "objective": "Convidar alguém e combinar um encontro.",
        "items": [
            ("Do you want to come?", "Você quer vir?", "Do you want to come with us?", "Você quer vir com a gente?"),
            ("Let us meet at four", "Vamos nos encontrar as quatro", "Let us meet at four at the park.", "Vamos nos encontrar as quatro no parque."),
            ("I would love to", "Eu adoraria", "A party? I would love to.", "Uma festa? Eu adoraria."),
            ("I cannot today", "Eu não posso hoje", "I cannot today, I have class.", "Eu não posso hoje, eu tenho aula."),
            ("Another day, maybe", "Outro dia, talvez", "Another day, maybe next week.", "Outro dia, talvez semana que vem."),
            ("Bring your friend", "Traga o seu amigo", "Bring your friend to the party.", "Traga o seu amigo para a festa."),
            ("It starts at six", "Comeca as seis", "The film starts at six.", "O filme comeca as seis."),
            ("Thanks for inviting me", "Obrigado por me convidar", "Thanks for inviting me to lunch.", "Obrigado por me convidar para o almoço."),
        ],
    },
    {
        "slug": "core_a2_29_people",
        "level": 4,
        "title": "Inglês A2 - Descrever pessoas",
        "theme": "Descrições",
        "objective": "Descrever como alguém é.",
        "items": [
            ("He is tall", "Ele é alto", "My brother is tall and thin.", "Meu irmão é alto e magro."),
            ("She is kind", "Ela é gentil", "She is kind to everyone.", "Ela é gentil com todos."),
            ("He is funny", "Ele é engraçado", "My cousin is very funny.", "Meu primo é muito engraçado."),
            ("She has curly hair", "Ela tem cabelo cacheado", "She has curly hair and brown eyes.", "Ela tem cabelo cacheado e olhos castanhos."),
            ("He wears glasses", "Ele usa óculos", "My teacher wears glasses.", "Meu professor usa óculos."),
            ("She is my best friend", "Ela é a minha melhor amiga", "She is my best friend at school.", "Ela é a minha melhor amiga na escola."),
            ("What is he like?", "Como ele é?", "What is he like as a teacher?", "Como ele é como professor?"),
            ("They look alike", "Eles são parecidos", "The twins look alike.", "Os gêmeos são parecidos."),
        ],
    },
    {
        "slug": "core_a2_30_story",
        "level": 4,
        "title": "Inglês A2 - Contar uma história",
        "theme": "Histórias",
        "objective": "Ligar as partes de uma história.",
        "items": [
            ("first", "primeiro", "First, we packed our bags.", "Primeiro, nós arrumamos as malas."),
            ("then", "então", "Then we took the bus.", "Então nós pegamos o ônibus."),
            ("after that", "depois disso", "After that we had lunch.", "Depois disso nós almoçamos."),
            ("finally", "finalmente", "Finally we arrived home.", "Finalmente nós chegamos em casa."),
            ("because", "porque", "I was late because of the rain.", "Eu me atrasei por causa da chuva."),
            ("but", "mas", "It was cold but sunny.", "Estava frio mas ensolarado."),
            ("suddenly", "de repente", "Suddenly the dog barked.", "De repente o cachorro latiu."),
            ("in the end", "no fim", "In the end everybody was happy.", "No fim todo mundo estava feliz."),
        ],
    },
]


# Word-by-word meanings for the phrases above. One place for the whole pack, so
# "my" is translated the same way in all thirty lessons. Lower-case keys; the
# builder strips punctuation before looking a word up.
GLOSSARY: dict[str, str] = {
    "a": "um",
    "about": "sobre",
    "afraid": "com medo",
    "after": "depois",
    "afternoon": "tarde",
    "again": "de novo",
    "ago": "atrás",
    "agree": "concordo",
    "ahead": "em frente",
    "alike": "parecidos",
    "am": "estou",
    "an": "uma",
    "ana": "Ana",
    "and": "e",
    "animals": "animais",
    "another": "outro",
    "apple": "maçã",
    "are": "está",
    "as": "tão",
    "at": "em",
    "backpack": "mochila",
    "ball": "bola",
    "bathroom": "banheiro",
    "be": "tenha",
    "beans": "feijão",
    "because": "porque",
    "bed": "cama",
    "bedroom": "quarto",
    "best": "melhor",
    "better": "melhor",
    "big": "grande",
    "bigger": "maior",
    "bird": "passaro",
    "black": "preto",
    "blue": "azul",
    "book": "livro",
    "books": "livros",
    "brazil": "Brasil",
    "bread": "pão",
    "bring": "traga",
    "brother": "irmão",
    "brush": "escovo",
    "bus": "ônibus",
    "but": "mas",
    "by": "de",
    "call": "chame",
    "can": "posso",
    "cannot": "não posso",
    "card": "cartão",
    "careful": "cuidado",
    "cat": "gato",
    "change": "troco",
    "cheap": "barato",
    "class": "aula",
    "classroom": "sala de aula",
    "close": "feche",
    "cold": "frio",
    "colour": "cor",
    "come": "vir",
    "cooking": "cozinhando",
    "course": "claro",
    "curly": "cacheado",
    "day": "dia",
    "days": "dias",
    "delicious": "delicioso",
    "depends": "depende",
    "did": "fez",
    "difficult": "difícil",
    "do": "faço",
    "doctor": "médico",
    "does": "faz",
    "dog": "cachorro",
    "dogs": "cachorros",
    "doing": "fazendo",
    "door": "porta",
    "dress": "vestido",
    "early": "cedo",
    "eat": "como",
    "eight": "oito",
    "emergency": "emergência",
    "end": "fim",
    "every": "todo",
    "excited": "animado",
    "excuse": "com licença",
    "expensive": "caro",
    "eyes": "olhos",
    "family": "família",
    "fast": "rápido",
    "father": "pai",
    "favourite": "favorita",
    "feel": "sinto",
    "fever": "febre",
    "film": "filme",
    "finally": "finalmente",
    "fine": "bem",
    "first": "primeiro",
    "fish": "peixe",
    "five": "cinco",
    "food": "comida",
    "foot": "pé",
    "for": "para",
    "forgets": "esquece",
    "four": "quatro",
    "friend": "amigo",
    "from": "de",
    "fun": "divertido",
    "funny": "engraçado",
    "game": "jogo",
    "get": "chego",
    "glasses": "óculos",
    "go": "vou",
    "going": "vou",
    "good": "bom",
    "goodbye": "tchau",
    "grandfather": "avó",
    "grandmother": "avó",
    "great": "ótimo",
    "green": "verde",
    "hair": "cabelo",
    "hand": "mão",
    "hands": "mãos",
    "happy": "feliz",
    "has": "tem",
    "hat": "chapéu",
    "have": "tenho",
    "he": "ele",
    "head": "cabeça",
    "hello": "oi",
    "help": "ajudo",
    "her": "dela",
    "here": "aqui",
    "home": "casa",
    "homework": "lição de casa",
    "hope": "espero",
    "horse": "cavalo",
    "hospital": "hospital",
    "hours": "horas",
    "house": "casa",
    "how": "como",
    "hungry": "com fome",
    "hurts": "dói",
    "i": "eu",
    "in": "em",
    "inviting": "convidar",
    "is": "e",
    "it": "isso",
    "jacket": "jaqueta",
    "just": "só",
    "kind": "gentil",
    "kitchen": "cozinha",
    "know": "sei",
    "last": "passada",
    "later": "mais tarde",
    "left": "esquerda",
    "less": "menos",
    "let": "vamos",
    "like": "gosto",
    "live": "moramos",
    "look": "olhe",
    "looking": "olhando",
    "lost": "perdido",
    "love": "amo",
    "lunch": "almoço",
    "many": "muitos",
    "market": "mercado",
    "may": "posso",
    "maybe": "talvez",
    "me": "mim",
    "medicine": "remédio",
    "meet": "conhecer",
    "milk": "leite",
    "moment": "momento",
    "monday": "segunda-feira",
    "more": "mais",
    "morning": "manhã",
    "mother": "mãe",
    "mouth": "boca",
    "much": "quanto",
    "music": "música",
    "my": "meu",
    "name": "nome",
    "near": "perto",
    "never": "nunca",
    "next": "próximo",
    "nice": "prazer",
    "night": "noite",
    "nine": "nove",
    "noisy": "barulhento",
    "not": "não",
    "now": "agora",
    "of": "de",
    "off": "fora",
    "okay": "bem",
    "old": "de idade",
    "on": "em",
    "one": "um",
    "out": "sair",
    "park": "parque",
    "pay": "pagar",
    "pencil": "lápis",
    "plane": "avião",
    "plans": "planos",
    "play": "jogam",
    "played": "joguei",
    "playing": "jogando",
    "please": "por favor",
    "portuguese": "português",
    "prefer": "prefiro",
    "promise": "prometo",
    "put": "calce",
    "question": "pergunta",
    "rabbit": "coelho",
    "raining": "chovendo",
    "reading": "lendo",
    "red": "vermelho",
    "repeat": "repetir",
    "rice": "arroz",
    "right": "agora",
    "sad": "triste",
    "same": "mesmo",
    "say": "diz",
    "school": "escola",
    "see": "ver",
    "seven": "sete",
    "she": "ela",
    "shirt": "camisa",
    "shoes": "sapatos",
    "should": "deveria",
    "sister": "irmã",
    "six": "seis",
    "size": "tamanho",
    "sleeping": "dormindo",
    "smaller": "menor",
    "so": "sim",
    "soon": "logo",
    "sorry": "desculpe",
    "speak": "falo",
    "starts": "comeca",
    "station": "estação",
    "stop": "ponto",
    "straight": "em frente",
    "studies": "estuda",
    "study": "estudo",
    "studying": "estudando",
    "suddenly": "de repente",
    "sunny": "ensolarado",
    "table": "mesa",
    "take": "tome",
    "takes": "leva",
    "tall": "alto",
    "tea": "chá",
    "teacher": "professor",
    "teeth": "dentes",
    "ten": "dez",
    "than": "que",
    "thank": "obrigado",
    "thanks": "obrigado",
    "that": "aquele",
    "the": "o",
    "then": "então",
    "there": "lá",
    "they": "eles",
    "think": "acha",
    "thirsty": "com sede",
    "this": "este",
    "three": "três",
    "throat": "garganta",
    "ticket": "passagem",
    "time": "hora",
    "tired": "cansado",
    "to": "para",
    "today": "hoje",
    "tomorrow": "amanhã",
    "too": "demais",
    "travel": "viajar",
    "twenty": "vinte",
    "trip": "viagem",
    "trousers": "calça",
    "try": "tentar",
    "turn": "vire",
    "two": "dois",
    "up": "acima",
    "us": "nos",
    "waiting": "esperar",
    "wake": "acordo",
    "want": "quer",
    "was": "foi",
    "wash": "lave",
    "watched": "assistimos",
    "water": "água",
    "we": "nos",
    "wearing": "usando",
    "wears": "usa",
    "week": "semana",
    "weekend": "fim de semana",
    "welcome": "de nada",
    "well": "bem",
    "went": "saiu",
    "what": "o que",
    "when": "quando",
    "where": "onde",
    "white": "branco",
    "who": "quem",
    "why": "por que",
    "will": "vai",
    "with": "com",
    "won": "ganhei",
    "works": "trabalha",
    "worry": "preocupe",
    "would": "queria",
    "years": "anos",
    "yellow": "amarelo",
    "yesterday": "ontem",
    "you": "você",
    "your": "seu",
}
