"""The curated English core pack: 30 lessons of 8 phrases, levels 1 to 4.

Why this exists: the app's fixed content was one three-phrase lesson per level,
so a child without an AI key (or with the day's credits spent) ran out of
material on the first afternoon. This pack is the floor the product stands on —
enough real English, written and checked by a person, that the app is useful
before a single provider call is made.

Shape of a lesson entry:

    slug      file name and stable identity of the lesson
    level     the child level it is shown at (1..4 here; A1 to A2)
    title     what the child sees
    theme     grouping, also used as the lesson's subject name
    objective one sentence about what the lesson is for
    items     8 tuples of (phrase_en, phrase_pt, example_en, example_pt)

`GLOSSARY` maps each word used in a *phrase* to its Portuguese meaning, which is
what builds the word-by-word breakdown the lesson screen shows. Keeping it in one
place is what keeps "my" translated the same way in all thirty lessons.

Run `python scripts/build_english_core_pack.py` after changing anything here.
"""

from __future__ import annotations

LESSONS: list[dict] = [
    # ── Level 1 · A1, the first words ─────────────────────────────────────────
    {
        "slug": "core_a1_01_greetings",
        "level": 1,
        "title": "Ingles A1 - Cumprimentos",
        "theme": "Cumprimentos",
        "objective": "Dizer oi, tchau e como voce esta.",
        "items": [
            ("Hello!", "Oi!", "Hello! Nice to see you.", "Oi! Que bom te ver."),
            ("Good morning", "Bom dia", "Good morning, teacher!", "Bom dia, professora!"),
            ("Good afternoon", "Boa tarde", "Good afternoon, everyone.", "Boa tarde, pessoal."),
            ("Good night", "Boa noite", "Good night, sleep well.", "Boa noite, durma bem."),
            ("How are you?", "Como voce esta?", "Hi Ana, how are you?", "Oi Ana, como voce esta?"),
            ("I am fine", "Eu estou bem", "I am fine, thank you.", "Eu estou bem, obrigado."),
            ("Nice to meet you", "Prazer em conhecer voce", "Nice to meet you, Lucas.", "Prazer em conhecer voce, Lucas."),
            ("Goodbye!", "Tchau!", "Goodbye! See you tomorrow.", "Tchau! Ate amanha."),
        ],
    },
    {
        "slug": "core_a1_02_about_me",
        "level": 1,
        "title": "Ingles A1 - Sobre mim",
        "theme": "Sobre mim",
        "objective": "Falar seu nome, sua idade e de onde voce e.",
        "items": [
            ("My name is Ana", "Meu nome e Ana", "Hello, my name is Ana.", "Ola, meu nome e Ana."),
            ("What is your name?", "Qual e o seu nome?", "Hi! What is your name?", "Oi! Qual e o seu nome?"),
            ("I am eight years old", "Eu tenho oito anos", "I am eight years old today.", "Eu tenho oito anos hoje."),
            ("How old are you?", "Quantos anos voce tem?", "How old are you, Lucas?", "Quantos anos voce tem, Lucas?"),
            ("I am from Brazil", "Eu sou do Brasil", "I am from Brazil, from Recife.", "Eu sou do Brasil, de Recife."),
            ("Where are you from?", "De onde voce e?", "Where are you from, Mia?", "De onde voce e, Mia?"),
            ("I speak Portuguese", "Eu falo portugues", "I speak Portuguese and English.", "Eu falo portugues e ingles."),
            ("This is my friend", "Este e o meu amigo", "This is my friend Pedro.", "Este e o meu amigo Pedro."),
        ],
    },
    {
        "slug": "core_a1_03_family",
        "level": 1,
        "title": "Ingles A1 - Familia",
        "theme": "Familia",
        "objective": "Falar das pessoas da sua familia.",
        "items": [
            ("my mother", "minha mae", "My mother cooks very well.", "Minha mae cozinha muito bem."),
            ("my father", "meu pai", "My father works in the city.", "Meu pai trabalha na cidade."),
            ("my sister", "minha irma", "My sister is six years old.", "Minha irma tem seis anos."),
            ("my brother", "meu irmao", "My brother plays football.", "Meu irmao joga futebol."),
            ("my grandmother", "minha avo", "My grandmother tells good stories.", "Minha avo conta boas historias."),
            ("my grandfather", "meu avo", "My grandfather has a garden.", "Meu avo tem um jardim."),
            ("I love my family", "Eu amo a minha familia", "I love my family very much.", "Eu amo muito a minha familia."),
            ("We are at home", "Nos estamos em casa", "We are at home today.", "Nos estamos em casa hoje."),
        ],
    },
    {
        "slug": "core_a1_04_numbers",
        "level": 1,
        "title": "Ingles A1 - Numeros",
        "theme": "Numeros",
        "objective": "Contar de um a dez e falar quantidades.",
        "items": [
            ("one, two, three", "um, dois, tres", "Count with me: one, two, three.", "Conte comigo: um, dois, tres."),
            ("four, five, six", "quatro, cinco, seis", "I have four, five, six pencils.", "Eu tenho quatro, cinco, seis lapis."),
            ("seven, eight, nine", "sete, oito, nove", "Seven, eight, nine birds are here.", "Sete, oito, nove passaros estao aqui."),
            ("ten", "dez", "There are ten children here.", "Ha dez criancas aqui."),
            ("How many?", "Quantos?", "How many apples do you have?", "Quantas macas voce tem?"),
            ("I have two dogs", "Eu tenho dois cachorros", "I have two dogs at home.", "Eu tenho dois cachorros em casa."),
            ("the first one", "o primeiro", "The first one is mine.", "O primeiro e meu."),
            ("many books", "muitos livros", "She reads many books.", "Ela le muitos livros."),
        ],
    },
    {
        "slug": "core_a1_05_colours",
        "level": 1,
        "title": "Ingles A1 - Cores",
        "theme": "Cores",
        "objective": "Falar as cores das coisas ao seu redor.",
        "items": [
            ("red", "vermelho", "The apple is red.", "A maca e vermelha."),
            ("blue", "azul", "The sky is blue today.", "O ceu esta azul hoje."),
            ("green", "verde", "The grass is green.", "A grama e verde."),
            ("yellow", "amarelo", "The sun looks yellow.", "O sol parece amarelo."),
            ("black", "preto", "My cat is black.", "Meu gato e preto."),
            ("white", "branco", "The paper is white.", "O papel e branco."),
            ("What colour is it?", "Que cor e?", "What colour is your bag?", "Que cor e a sua mochila?"),
            ("my favourite colour", "minha cor favorita", "Green is my favourite colour.", "Verde e a minha cor favorita."),
        ],
    },
    {
        "slug": "core_a1_06_animals",
        "level": 1,
        "title": "Ingles A1 - Animais",
        "theme": "Animais",
        "objective": "Nomear animais e dizer o que eles fazem.",
        "items": [
            ("a dog", "um cachorro", "A dog runs in the park.", "Um cachorro corre no parque."),
            ("a cat", "um gato", "A cat sleeps on the sofa.", "Um gato dorme no sofa."),
            ("a bird", "um passaro", "A bird sings in the tree.", "Um passaro canta na arvore."),
            ("a fish", "um peixe", "A fish swims in the water.", "Um peixe nada na agua."),
            ("a horse", "um cavalo", "A horse eats grass.", "Um cavalo come grama."),
            ("a rabbit", "um coelho", "A rabbit jumps very fast.", "Um coelho pula muito rapido."),
            ("I like animals", "Eu gosto de animais", "I like animals, especially cats.", "Eu gosto de animais, especialmente gatos."),
            ("the animals eat", "os animais comem", "The animals eat in the morning.", "Os animais comem de manha."),
        ],
    },
    {
        "slug": "core_a1_07_food",
        "level": 1,
        "title": "Ingles A1 - Comida",
        "theme": "Comida",
        "objective": "Falar de comida e bebida do dia a dia.",
        "items": [
            ("bread", "pao", "I eat bread for breakfast.", "Eu como pao no cafe da manha."),
            ("milk", "leite", "She drinks milk every morning.", "Ela bebe leite toda manha."),
            ("water", "agua", "Please give me water.", "Por favor me de agua."),
            ("an apple", "uma maca", "An apple is a good snack.", "Uma maca e um bom lanche."),
            ("rice and beans", "arroz e feijao", "We eat rice and beans at lunch.", "Nos comemos arroz e feijao no almoco."),
            ("I am hungry", "Eu estou com fome", "I am hungry, let us eat.", "Eu estou com fome, vamos comer."),
            ("I am thirsty", "Eu estou com sede", "I am thirsty after the game.", "Eu estou com sede depois do jogo."),
            ("It is delicious", "Esta delicioso", "This cake is delicious.", "Este bolo esta delicioso."),
        ],
    },
    {
        "slug": "core_a1_08_school",
        "level": 1,
        "title": "Ingles A1 - Na escola",
        "theme": "Escola",
        "objective": "Falar das coisas e das pessoas da escola.",
        "items": [
            ("my school", "minha escola", "My school is near my house.", "Minha escola e perto da minha casa."),
            ("my teacher", "meu professor", "My teacher is very kind.", "Meu professor e muito gentil."),
            ("a book", "um livro", "I read a book every night.", "Eu leio um livro toda noite."),
            ("a pencil", "um lapis", "I write with a pencil.", "Eu escrevo com um lapis."),
            ("my backpack", "minha mochila", "My backpack is heavy today.", "Minha mochila esta pesada hoje."),
            ("the classroom", "a sala de aula", "The classroom is big and bright.", "A sala de aula e grande e clara."),
            ("I study every day", "Eu estudo todo dia", "I study every day after school.", "Eu estudo todo dia depois da escola."),
            ("May I go out?", "Posso sair?", "Teacher, may I go out?", "Professora, posso sair?"),
        ],
    },
    # ── Level 2 · A1, the everyday world ──────────────────────────────────────
    {
        "slug": "core_a1_09_feelings",
        "level": 2,
        "title": "Ingles A1 - Sentimentos",
        "theme": "Sentimentos",
        "objective": "Dizer como voce se sente hoje.",
        "items": [
            ("I am happy", "Eu estou feliz", "I am happy to see you.", "Eu estou feliz em te ver."),
            ("I am sad", "Eu estou triste", "I am sad because it is raining.", "Eu estou triste porque esta chovendo."),
            ("I am tired", "Eu estou cansado", "I am tired after the game.", "Eu estou cansado depois do jogo."),
            ("I am afraid", "Eu estou com medo", "I am afraid of the dark.", "Eu estou com medo do escuro."),
            ("I am excited", "Eu estou animado", "I am excited about the trip.", "Eu estou animado com a viagem."),
            ("Are you okay?", "Voce esta bem?", "Are you okay, my friend?", "Voce esta bem, meu amigo?"),
            ("Do not worry", "Nao se preocupe", "Do not worry, I am here.", "Nao se preocupe, eu estou aqui."),
            ("I feel better now", "Eu me sinto melhor agora", "I feel better now, thank you.", "Eu me sinto melhor agora, obrigado."),
        ],
    },
    {
        "slug": "core_a1_10_body",
        "level": 2,
        "title": "Ingles A1 - O corpo",
        "theme": "Corpo",
        "objective": "Nomear partes do corpo.",
        "items": [
            ("my head", "minha cabeca", "My head hurts a little.", "Minha cabeca doi um pouco."),
            ("my hand", "minha mao", "I write with my hand.", "Eu escrevo com a minha mao."),
            ("my foot", "meu pe", "My foot is in the water.", "Meu pe esta na agua."),
            ("my eyes", "meus olhos", "My eyes are brown.", "Meus olhos sao castanhos."),
            ("my hair", "meu cabelo", "My hair is long and black.", "Meu cabelo e longo e preto."),
            ("my mouth", "minha boca", "I open my mouth to speak.", "Eu abro a boca para falar."),
            ("Wash your hands", "Lave as maos", "Wash your hands before lunch.", "Lave as maos antes do almoco."),
            ("Look at me", "Olhe para mim", "Look at me, please.", "Olhe para mim, por favor."),
        ],
    },
    {
        "slug": "core_a1_11_clothes",
        "level": 2,
        "title": "Ingles A1 - Roupas",
        "theme": "Roupas",
        "objective": "Falar do que voce esta vestindo.",
        "items": [
            ("a shirt", "uma camisa", "He wears a blue shirt.", "Ele usa uma camisa azul."),
            ("trousers", "calca", "These trousers are new.", "Esta calca e nova."),
            ("shoes", "sapatos", "My shoes are dirty.", "Meus sapatos estao sujos."),
            ("a jacket", "uma jaqueta", "Take a jacket, it is cold.", "Leve uma jaqueta, esta frio."),
            ("a hat", "um chapeu", "She wears a hat in the sun.", "Ela usa um chapeu no sol."),
            ("I am wearing a dress", "Eu estou usando um vestido", "I am wearing a red dress.", "Eu estou usando um vestido vermelho."),
            ("Put on your shoes", "Calce os sapatos", "Put on your shoes, we are late.", "Calce os sapatos, estamos atrasados."),
            ("It is too big", "Esta grande demais", "This shirt is too big for me.", "Esta camisa esta grande demais para mim."),
        ],
    },
    {
        "slug": "core_a1_12_house",
        "level": 2,
        "title": "Ingles A1 - Em casa",
        "theme": "Casa",
        "objective": "Falar dos comodos e das coisas de casa.",
        "items": [
            ("my house", "minha casa", "My house has a small garden.", "Minha casa tem um jardim pequeno."),
            ("the kitchen", "a cozinha", "We cook in the kitchen.", "Nos cozinhamos na cozinha."),
            ("my bedroom", "meu quarto", "My bedroom is upstairs.", "Meu quarto fica em cima."),
            ("the bathroom", "o banheiro", "The bathroom is on the left.", "O banheiro fica a esquerda."),
            ("a table", "uma mesa", "We eat at the table.", "Nos comemos a mesa."),
            ("a bed", "uma cama", "My bed is very soft.", "Minha cama e bem macia."),
            ("Come in, please", "Entre, por favor", "Come in, please, it is open.", "Entre, por favor, esta aberto."),
            ("Close the door", "Feche a porta", "Close the door, it is cold.", "Feche a porta, esta frio."),
        ],
    },
    {
        "slug": "core_a1_13_play",
        "level": 2,
        "title": "Ingles A1 - Brincar",
        "theme": "Brincadeiras",
        "objective": "Falar de brincadeiras e jogos.",
        "items": [
            ("Let us play", "Vamos brincar", "Let us play in the garden.", "Vamos brincar no jardim."),
            ("a ball", "uma bola", "Throw me the ball, please.", "Jogue a bola para mim, por favor."),
            ("a game", "um jogo", "This game is really fun.", "Este jogo e bem divertido."),
            ("my turn", "minha vez", "It is my turn now.", "Agora e a minha vez."),
            ("your turn", "sua vez", "It is your turn, go ahead.", "E a sua vez, pode ir."),
            ("I won!", "Eu ganhei!", "I won the game!", "Eu ganhei o jogo!"),
            ("Let us try again", "Vamos tentar de novo", "Let us try again tomorrow.", "Vamos tentar de novo amanha."),
            ("That is fun", "Isso e divertido", "Riding a bike is fun.", "Andar de bicicleta e divertido."),
        ],
    },
    {
        "slug": "core_a1_14_time_weather",
        "level": 2,
        "title": "Ingles A1 - Dias e tempo",
        "theme": "Dias e tempo",
        "objective": "Falar dos dias da semana e do tempo.",
        "items": [
            ("today", "hoje", "Today is a good day.", "Hoje e um bom dia."),
            ("tomorrow", "amanha", "Tomorrow we go to school.", "Amanha nos vamos para a escola."),
            ("yesterday", "ontem", "Yesterday was very hot.", "Ontem estava muito quente."),
            ("on Monday", "na segunda-feira", "On Monday I have English.", "Na segunda-feira eu tenho ingles."),
            ("It is sunny", "Esta ensolarado", "It is sunny, let us go out.", "Esta ensolarado, vamos sair."),
            ("It is raining", "Esta chovendo", "It is raining a lot today.", "Esta chovendo muito hoje."),
            ("It is cold", "Esta frio", "It is cold in the morning.", "Esta frio de manha."),
            ("What time is it?", "Que horas sao?", "What time is it, please?", "Que horas sao, por favor?"),
        ],
    },
    {
        "slug": "core_a1_15_polite",
        "level": 2,
        "title": "Ingles A1 - Pedir com educacao",
        "theme": "Pedidos",
        "objective": "Pedir as coisas com educacao.",
        "items": [
            ("please", "por favor", "Can you help me, please?", "Voce pode me ajudar, por favor?"),
            ("thank you", "obrigado", "Thank you for your help.", "Obrigado pela sua ajuda."),
            ("You are welcome", "De nada", "You are welcome, my friend.", "De nada, meu amigo."),
            ("I am sorry", "Me desculpe", "I am sorry, it was my mistake.", "Me desculpe, foi erro meu."),
            ("Excuse me", "Com licenca", "Excuse me, where is the door?", "Com licenca, onde fica a porta?"),
            ("Can I help you?", "Posso ajudar?", "Can I help you with that?", "Posso ajudar com isso?"),
            ("May I have water?", "Posso pegar agua?", "May I have water, please?", "Posso pegar agua, por favor?"),
            ("Of course", "Claro", "Of course, take it.", "Claro, pode pegar."),
        ],
    },
    {
        "slug": "core_a1_16_questions",
        "level": 2,
        "title": "Ingles A1 - Perguntas simples",
        "theme": "Perguntas",
        "objective": "Fazer perguntas basicas com what, where e who.",
        "items": [
            ("What is this?", "O que e isto?", "What is this in English?", "O que e isto em ingles?"),
            ("Where is it?", "Onde esta?", "Where is my pencil?", "Onde esta o meu lapis?"),
            ("Who is that?", "Quem e aquele?", "Who is that boy over there?", "Quem e aquele menino ali?"),
            ("Why not?", "Por que nao?", "Why not try again?", "Por que nao tentar de novo?"),
            ("When is the class?", "Quando e a aula?", "When is the English class?", "Quando e a aula de ingles?"),
            ("How do you say it?", "Como se diz?", "How do you say it in Portuguese?", "Como se diz isso em portugues?"),
            ("Can you repeat?", "Voce pode repetir?", "Can you repeat that, please?", "Voce pode repetir isso, por favor?"),
            ("I do not know", "Eu nao sei", "I do not know the answer.", "Eu nao sei a resposta."),
        ],
    },
    # ── Level 3 · A2, routine and opinion ─────────────────────────────────────
    {
        "slug": "core_a2_17_routine",
        "level": 3,
        "title": "Ingles A2 - Rotina",
        "theme": "Rotina",
        "objective": "Contar o que voce faz todos os dias.",
        "items": [
            ("I wake up early", "Eu acordo cedo", "I wake up early every day.", "Eu acordo cedo todo dia."),
            ("I brush my teeth", "Eu escovo os dentes", "I brush my teeth after breakfast.", "Eu escovo os dentes depois do cafe."),
            ("I go to school", "Eu vou para a escola", "I go to school at seven.", "Eu vou para a escola as sete."),
            ("I do my homework", "Eu faco a minha licao", "I do my homework in the afternoon.", "Eu faco a minha licao a tarde."),
            ("I help at home", "Eu ajudo em casa", "I help at home on Saturdays.", "Eu ajudo em casa aos sabados."),
            ("I go to bed at nine", "Eu vou dormir as nove", "I go to bed at nine o'clock.", "Eu vou dormir as nove horas."),
            ("every morning", "toda manha", "Every morning I drink milk.", "Toda manha eu bebo leite."),
            ("after lunch", "depois do almoco", "After lunch I read a book.", "Depois do almoco eu leio um livro."),
        ],
    },
    {
        "slug": "core_a2_18_verbs",
        "level": 3,
        "title": "Ingles A2 - Verbos do dia a dia",
        "theme": "Verbos",
        "objective": "Usar verbos comuns no presente.",
        "items": [
            ("I eat", "Eu como", "I eat fruit every day.", "Eu como fruta todo dia."),
            ("She works", "Ela trabalha", "She works at a hospital.", "Ela trabalha em um hospital."),
            ("He studies", "Ele estuda", "He studies English at night.", "Ele estuda ingles a noite."),
            ("We live here", "Nos moramos aqui", "We live here with our dog.", "Nos moramos aqui com o nosso cachorro."),
            ("They play", "Eles brincam", "They play in the park.", "Eles brincam no parque."),
            ("I do not like it", "Eu nao gosto disso", "I do not like cold soup.", "Eu nao gosto de sopa fria."),
            ("Does she know?", "Ela sabe?", "Does she know the answer?", "Ela sabe a resposta?"),
            ("He never forgets", "Ele nunca esquece", "He never forgets my birthday.", "Ele nunca esquece o meu aniversario."),
        ],
    },
    {
        "slug": "core_a2_19_likes",
        "level": 3,
        "title": "Ingles A2 - Gostos",
        "theme": "Gostos",
        "objective": "Dizer do que voce gosta e do que nao gosta.",
        "items": [
            ("I like music", "Eu gosto de musica", "I like music from Brazil.", "Eu gosto de musica do Brasil."),
            ("I love reading", "Eu amo ler", "I love reading before bed.", "Eu amo ler antes de dormir."),
            ("I do not like waiting", "Eu nao gosto de esperar", "I do not like waiting in line.", "Eu nao gosto de esperar na fila."),
            ("My favourite food", "Minha comida favorita", "My favourite food is pizza.", "Minha comida favorita e pizza."),
            ("I prefer tea", "Eu prefiro cha", "I prefer tea to coffee.", "Eu prefiro cha a cafe."),
            ("What do you think?", "O que voce acha?", "What do you think about this song?", "O que voce acha desta musica?"),
            ("I agree with you", "Eu concordo com voce", "I agree with you about the film.", "Eu concordo com voce sobre o filme."),
            ("It depends", "Depende", "It depends on the weather.", "Depende do tempo."),
        ],
    },
    {
        "slug": "core_a2_20_places",
        "level": 3,
        "title": "Ingles A2 - Lugares",
        "theme": "Lugares",
        "objective": "Falar de lugares da cidade e como chegar.",
        "items": [
            ("the park", "o parque", "The park is next to my house.", "O parque fica ao lado da minha casa."),
            ("the market", "o mercado", "We buy fruit at the market.", "Nos compramos fruta no mercado."),
            ("the hospital", "o hospital", "The hospital is far from here.", "O hospital fica longe daqui."),
            ("the bus stop", "o ponto de onibus", "I wait at the bus stop.", "Eu espero no ponto de onibus."),
            ("Turn left", "Vire a esquerda", "Turn left at the corner.", "Vire a esquerda na esquina."),
            ("Go straight ahead", "Siga em frente", "Go straight ahead for two streets.", "Siga em frente por duas ruas."),
            ("It is near here", "E perto daqui", "The school is near here.", "A escola e perto daqui."),
            ("How do I get there?", "Como eu chego la?", "How do I get there by bus?", "Como eu chego la de onibus?"),
        ],
    },
    {
        "slug": "core_a2_21_shopping",
        "level": 3,
        "title": "Ingles A2 - Compras",
        "theme": "Compras",
        "objective": "Comprar coisas e perguntar o preco.",
        "items": [
            ("How much is it?", "Quanto custa?", "How much is this book?", "Quanto custa este livro?"),
            ("It is expensive", "Esta caro", "This jacket is expensive.", "Esta jaqueta esta cara."),
            ("It is cheap", "Esta barato", "The bread is cheap here.", "O pao e barato aqui."),
            ("I would like this one", "Eu queria este", "I would like this one, please.", "Eu queria este, por favor."),
            ("Do you have a bigger size?", "Voce tem um tamanho maior?", "Do you have a bigger size, please?", "Voce tem um tamanho maior, por favor?"),
            ("I am just looking", "Eu so estou olhando", "Thank you, I am just looking.", "Obrigado, eu so estou olhando."),
            ("Can I pay by card?", "Posso pagar com cartao?", "Can I pay by card here?", "Posso pagar com cartao aqui?"),
            ("Here is your change", "Aqui esta o seu troco", "Here is your change, thank you.", "Aqui esta o seu troco, obrigado."),
        ],
    },
    {
        "slug": "core_a2_22_travel",
        "level": 3,
        "title": "Ingles A2 - Viagem",
        "theme": "Viagem",
        "objective": "Falar de viagens e transporte.",
        "items": [
            ("a trip", "uma viagem", "We are planning a trip.", "Nos estamos planejando uma viagem."),
            ("by bus", "de onibus", "I go to school by bus.", "Eu vou para a escola de onibus."),
            ("by plane", "de aviao", "They travel by plane.", "Eles viajam de aviao."),
            ("a ticket", "uma passagem", "I need a ticket to Rio.", "Eu preciso de uma passagem para o Rio."),
            ("Where is the station?", "Onde fica a estacao?", "Excuse me, where is the station?", "Com licenca, onde fica a estacao?"),
            ("I am lost", "Eu estou perdido", "I am lost, can you help me?", "Eu estou perdido, voce pode me ajudar?"),
            ("It takes two hours", "Leva duas horas", "The trip takes two hours.", "A viagem leva duas horas."),
            ("Have a good trip", "Boa viagem", "Have a good trip, see you soon.", "Boa viagem, ate logo."),
        ],
    },
    {
        "slug": "core_a2_23_now",
        "level": 3,
        "title": "Ingles A2 - Agora mesmo",
        "theme": "Presente continuo",
        "objective": "Dizer o que esta acontecendo agora.",
        "items": [
            ("I am reading", "Eu estou lendo", "I am reading a funny book.", "Eu estou lendo um livro engracado."),
            ("She is cooking", "Ela esta cozinhando", "She is cooking dinner now.", "Ela esta cozinhando o jantar agora."),
            ("They are playing", "Eles estao brincando", "They are playing outside.", "Eles estao brincando la fora."),
            ("We are studying", "Nos estamos estudando", "We are studying for the test.", "Nos estamos estudando para a prova."),
            ("What are you doing?", "O que voce esta fazendo?", "What are you doing right now?", "O que voce esta fazendo agora?"),
            ("I am not sleeping", "Eu nao estou dormindo", "I am not sleeping, I am thinking.", "Eu nao estou dormindo, eu estou pensando."),
            ("right now", "agora mesmo", "I am busy right now.", "Eu estou ocupado agora mesmo."),
            ("at the moment", "no momento", "He is away at the moment.", "Ele esta fora no momento."),
        ],
    },
    # ── Level 4 · A2, telling a story ─────────────────────────────────────────
    {
        "slug": "core_a2_24_past",
        "level": 4,
        "title": "Ingles A2 - Ontem",
        "theme": "Passado",
        "objective": "Contar o que aconteceu no passado.",
        "items": [
            ("I played", "Eu joguei", "I played football yesterday.", "Eu joguei futebol ontem."),
            ("She went out", "Ela saiu", "She went out with her friends.", "Ela saiu com as amigas."),
            ("We watched a film", "Nos assistimos a um filme", "We watched a film last night.", "Nos assistimos a um filme ontem a noite."),
            ("He did not come", "Ele nao veio", "He did not come to the party.", "Ele nao veio a festa."),
            ("Did you see it?", "Voce viu?", "Did you see the game?", "Voce viu o jogo?"),
            ("last week", "semana passada", "I was sick last week.", "Eu estava doente semana passada."),
            ("two days ago", "dois dias atras", "She called me two days ago.", "Ela me ligou dois dias atras."),
            ("It was great", "Foi otimo", "The trip was great.", "A viagem foi otima."),
        ],
    },
    {
        "slug": "core_a2_25_plans",
        "level": 4,
        "title": "Ingles A2 - Planos",
        "theme": "Planos",
        "objective": "Falar de planos e do futuro.",
        "items": [
            ("I am going to study", "Eu vou estudar", "I am going to study tonight.", "Eu vou estudar hoje a noite."),
            ("We will travel", "Nos vamos viajar", "We will travel in July.", "Nos vamos viajar em julho."),
            ("Next weekend", "No proximo fim de semana", "Next weekend we visit grandma.", "No proximo fim de semana nos visitamos a vovo."),
            ("What are your plans?", "Quais sao os seus planos?", "What are your plans for today?", "Quais sao os seus planos para hoje?"),
            ("Maybe later", "Talvez mais tarde", "Maybe later we can play.", "Talvez mais tarde a gente possa brincar."),
            ("I hope so", "Eu espero que sim", "Will it be sunny? I hope so.", "Vai fazer sol? Eu espero que sim."),
            ("I promise", "Eu prometo", "I promise I will help you.", "Eu prometo que vou te ajudar."),
            ("See you soon", "Ate logo", "See you soon, take care.", "Ate logo, se cuida."),
        ],
    },
    {
        "slug": "core_a2_26_compare",
        "level": 4,
        "title": "Ingles A2 - Comparar",
        "theme": "Comparacoes",
        "objective": "Comparar coisas e pessoas.",
        "items": [
            ("bigger than", "maior que", "My dog is bigger than yours.", "Meu cachorro e maior que o seu."),
            ("smaller than", "menor que", "This box is smaller than that one.", "Esta caixa e menor que aquela."),
            ("better than", "melhor que", "This book is better than the film.", "Este livro e melhor que o filme."),
            ("the best", "o melhor", "She is the best in the class.", "Ela e a melhor da turma."),
            ("the same", "o mesmo", "We have the same bag.", "Nos temos a mesma mochila."),
            ("as fast as", "tao rapido quanto", "He runs as fast as me.", "Ele corre tao rapido quanto eu."),
            ("more difficult", "mais dificil", "This exercise is more difficult.", "Este exercicio e mais dificil."),
            ("less noisy", "menos barulhento", "The new room is less noisy.", "A sala nova e menos barulhenta."),
        ],
    },
    {
        "slug": "core_a2_27_health",
        "level": 4,
        "title": "Ingles A2 - Saude",
        "theme": "Saude",
        "objective": "Dizer o que esta doendo e pedir ajuda.",
        "items": [
            ("I do not feel well", "Eu nao estou me sentindo bem", "I do not feel well today.", "Eu nao estou me sentindo bem hoje."),
            ("My throat hurts", "Minha garganta doi", "My throat hurts since yesterday.", "Minha garganta doi desde ontem."),
            ("I have a fever", "Eu estou com febre", "I have a fever and a cough.", "Eu estou com febre e tosse."),
            ("Call the doctor", "Chame o medico", "Call the doctor, please.", "Chame o medico, por favor."),
            ("Take this medicine", "Tome este remedio", "Take this medicine after lunch.", "Tome este remedio depois do almoco."),
            ("Get well soon", "Melhoras", "Get well soon, my friend.", "Melhoras, meu amigo."),
            ("Be careful", "Tenha cuidado", "Be careful with the stairs.", "Tenha cuidado com a escada."),
            ("It is an emergency", "E uma emergencia", "Help, it is an emergency!", "Socorro, e uma emergencia!"),
        ],
    },
    {
        "slug": "core_a2_28_invite",
        "level": 4,
        "title": "Ingles A2 - Convites",
        "theme": "Convites",
        "objective": "Convidar alguem e combinar um encontro.",
        "items": [
            ("Do you want to come?", "Voce quer vir?", "Do you want to come with us?", "Voce quer vir com a gente?"),
            ("Let us meet at four", "Vamos nos encontrar as quatro", "Let us meet at four at the park.", "Vamos nos encontrar as quatro no parque."),
            ("I would love to", "Eu adoraria", "A party? I would love to.", "Uma festa? Eu adoraria."),
            ("I cannot today", "Eu nao posso hoje", "I cannot today, I have class.", "Eu nao posso hoje, eu tenho aula."),
            ("Another day, maybe", "Outro dia, talvez", "Another day, maybe next week.", "Outro dia, talvez semana que vem."),
            ("Bring your friend", "Traga o seu amigo", "Bring your friend to the party.", "Traga o seu amigo para a festa."),
            ("It starts at six", "Comeca as seis", "The film starts at six.", "O filme comeca as seis."),
            ("Thanks for inviting me", "Obrigado por me convidar", "Thanks for inviting me to lunch.", "Obrigado por me convidar para o almoco."),
        ],
    },
    {
        "slug": "core_a2_29_people",
        "level": 4,
        "title": "Ingles A2 - Descrever pessoas",
        "theme": "Descricoes",
        "objective": "Descrever como alguem e.",
        "items": [
            ("He is tall", "Ele e alto", "My brother is tall and thin.", "Meu irmao e alto e magro."),
            ("She is kind", "Ela e gentil", "She is kind to everyone.", "Ela e gentil com todos."),
            ("He is funny", "Ele e engracado", "My cousin is very funny.", "Meu primo e muito engracado."),
            ("She has curly hair", "Ela tem cabelo cacheado", "She has curly hair and brown eyes.", "Ela tem cabelo cacheado e olhos castanhos."),
            ("He wears glasses", "Ele usa oculos", "My teacher wears glasses.", "Meu professor usa oculos."),
            ("She is my best friend", "Ela e a minha melhor amiga", "She is my best friend at school.", "Ela e a minha melhor amiga na escola."),
            ("What is he like?", "Como ele e?", "What is he like as a teacher?", "Como ele e como professor?"),
            ("They look alike", "Eles sao parecidos", "The twins look alike.", "Os gemeos sao parecidos."),
        ],
    },
    {
        "slug": "core_a2_30_story",
        "level": 4,
        "title": "Ingles A2 - Contar uma historia",
        "theme": "Historias",
        "objective": "Ligar as partes de uma historia.",
        "items": [
            ("first", "primeiro", "First, we packed our bags.", "Primeiro, nos arrumamos as malas."),
            ("then", "entao", "Then we took the bus.", "Entao nos pegamos o onibus."),
            ("after that", "depois disso", "After that we had lunch.", "Depois disso nos almocamos."),
            ("finally", "finalmente", "Finally we arrived home.", "Finalmente nos chegamos em casa."),
            ("because", "porque", "I was late because of the rain.", "Eu me atrasei por causa da chuva."),
            ("but", "mas", "It was cold but sunny.", "Estava frio mas ensolarado."),
            ("suddenly", "de repente", "Suddenly the dog barked.", "De repente o cachorro latiu."),
            ("in the end", "no fim", "In the end everybody was happy.", "No fim todo mundo estava feliz."),
        ],
    },
]


# Word-by-word meanings for the phrases above. One place for the whole pack, so
# "my" is translated the same way in all thirty lessons. Lower-case keys; the
# builder strips punctuation before looking a word up.
GLOSSARY: dict[str, str] = {
    "a": "um",
    "about": "sobre",
    "afraid": "com medo",
    "after": "depois",
    "afternoon": "tarde",
    "again": "de novo",
    "ago": "atras",
    "agree": "concordo",
    "ahead": "em frente",
    "alike": "parecidos",
    "am": "estou",
    "an": "uma",
    "ana": "Ana",
    "and": "e",
    "animals": "animais",
    "another": "outro",
    "apple": "maca",
    "are": "esta",
    "as": "tao",
    "at": "em",
    "backpack": "mochila",
    "ball": "bola",
    "bathroom": "banheiro",
    "be": "tenha",
    "beans": "feijao",
    "because": "porque",
    "bed": "cama",
    "bedroom": "quarto",
    "best": "melhor",
    "better": "melhor",
    "big": "grande",
    "bigger": "maior",
    "bird": "passaro",
    "black": "preto",
    "blue": "azul",
    "book": "livro",
    "books": "livros",
    "brazil": "Brasil",
    "bread": "pao",
    "bring": "traga",
    "brother": "irmao",
    "brush": "escovo",
    "bus": "onibus",
    "but": "mas",
    "by": "de",
    "call": "chame",
    "can": "posso",
    "cannot": "nao posso",
    "card": "cartao",
    "careful": "cuidado",
    "cat": "gato",
    "change": "troco",
    "cheap": "barato",
    "class": "aula",
    "classroom": "sala de aula",
    "close": "feche",
    "cold": "frio",
    "colour": "cor",
    "come": "vir",
    "cooking": "cozinhando",
    "course": "claro",
    "curly": "cacheado",
    "day": "dia",
    "days": "dias",
    "delicious": "delicioso",
    "depends": "depende",
    "did": "fez",
    "difficult": "dificil",
    "do": "faco",
    "doctor": "medico",
    "does": "faz",
    "dog": "cachorro",
    "dogs": "cachorros",
    "doing": "fazendo",
    "door": "porta",
    "dress": "vestido",
    "early": "cedo",
    "eat": "como",
    "eight": "oito",
    "emergency": "emergencia",
    "end": "fim",
    "every": "todo",
    "excited": "animado",
    "excuse": "com licenca",
    "expensive": "caro",
    "eyes": "olhos",
    "family": "familia",
    "fast": "rapido",
    "father": "pai",
    "favourite": "favorita",
    "feel": "sinto",
    "fever": "febre",
    "film": "filme",
    "finally": "finalmente",
    "fine": "bem",
    "first": "primeiro",
    "fish": "peixe",
    "five": "cinco",
    "food": "comida",
    "foot": "pe",
    "for": "para",
    "forgets": "esquece",
    "four": "quatro",
    "friend": "amigo",
    "from": "de",
    "fun": "divertido",
    "funny": "engracado",
    "game": "jogo",
    "get": "chego",
    "glasses": "oculos",
    "go": "vou",
    "going": "vou",
    "good": "bom",
    "goodbye": "tchau",
    "grandfather": "avo",
    "grandmother": "avo",
    "great": "otimo",
    "green": "verde",
    "hair": "cabelo",
    "hand": "mao",
    "hands": "maos",
    "happy": "feliz",
    "has": "tem",
    "hat": "chapeu",
    "have": "tenho",
    "he": "ele",
    "head": "cabeca",
    "hello": "oi",
    "help": "ajudo",
    "her": "dela",
    "here": "aqui",
    "home": "casa",
    "homework": "licao de casa",
    "hope": "espero",
    "horse": "cavalo",
    "hospital": "hospital",
    "hours": "horas",
    "house": "casa",
    "how": "como",
    "hungry": "com fome",
    "hurts": "doi",
    "i": "eu",
    "in": "em",
    "inviting": "convidar",
    "is": "e",
    "it": "isso",
    "jacket": "jaqueta",
    "just": "so",
    "kind": "gentil",
    "kitchen": "cozinha",
    "know": "sei",
    "last": "passada",
    "later": "mais tarde",
    "left": "esquerda",
    "less": "menos",
    "let": "vamos",
    "like": "gosto",
    "live": "moramos",
    "look": "olhe",
    "looking": "olhando",
    "lost": "perdido",
    "love": "amo",
    "lunch": "almoco",
    "many": "muitos",
    "market": "mercado",
    "may": "posso",
    "maybe": "talvez",
    "me": "mim",
    "medicine": "remedio",
    "meet": "conhecer",
    "milk": "leite",
    "moment": "momento",
    "monday": "segunda-feira",
    "more": "mais",
    "morning": "manha",
    "mother": "mae",
    "mouth": "boca",
    "much": "quanto",
    "music": "musica",
    "my": "meu",
    "name": "nome",
    "near": "perto",
    "never": "nunca",
    "next": "proximo",
    "nice": "prazer",
    "night": "noite",
    "nine": "nove",
    "noisy": "barulhento",
    "not": "nao",
    "now": "agora",
    "of": "de",
    "off": "fora",
    "okay": "bem",
    "old": "de idade",
    "on": "em",
    "one": "um",
    "out": "sair",
    "park": "parque",
    "pay": "pagar",
    "pencil": "lapis",
    "plane": "aviao",
    "plans": "planos",
    "play": "brincam",
    "played": "joguei",
    "playing": "brincando",
    "please": "por favor",
    "portuguese": "portugues",
    "prefer": "prefiro",
    "promise": "prometo",
    "put": "calce",
    "rabbit": "coelho",
    "raining": "chovendo",
    "reading": "lendo",
    "red": "vermelho",
    "repeat": "repetir",
    "rice": "arroz",
    "right": "agora",
    "sad": "triste",
    "same": "mesmo",
    "say": "diz",
    "school": "escola",
    "see": "ver",
    "seven": "sete",
    "she": "ela",
    "shirt": "camisa",
    "shoes": "sapatos",
    "should": "deveria",
    "sister": "irma",
    "six": "seis",
    "size": "tamanho",
    "sleeping": "dormindo",
    "smaller": "menor",
    "so": "sim",
    "soon": "logo",
    "sorry": "desculpe",
    "speak": "falo",
    "starts": "comeca",
    "station": "estacao",
    "stop": "ponto",
    "straight": "em frente",
    "studies": "estuda",
    "study": "estudo",
    "studying": "estudando",
    "suddenly": "de repente",
    "sunny": "ensolarado",
    "table": "mesa",
    "take": "tome",
    "takes": "leva",
    "tall": "alto",
    "tea": "cha",
    "teacher": "professor",
    "teeth": "dentes",
    "ten": "dez",
    "than": "que",
    "thank": "obrigado",
    "thanks": "obrigado",
    "that": "aquele",
    "the": "o",
    "then": "entao",
    "there": "la",
    "they": "eles",
    "think": "acha",
    "thirsty": "com sede",
    "this": "este",
    "three": "tres",
    "throat": "garganta",
    "ticket": "passagem",
    "time": "hora",
    "tired": "cansado",
    "to": "para",
    "today": "hoje",
    "tomorrow": "amanha",
    "too": "demais",
    "travel": "viajar",
    "trip": "viagem",
    "trousers": "calca",
    "try": "tentar",
    "turn": "vire",
    "two": "dois",
    "up": "acima",
    "us": "nos",
    "waiting": "esperar",
    "wake": "acordo",
    "want": "quer",
    "was": "foi",
    "wash": "lave",
    "watched": "assistimos",
    "water": "agua",
    "we": "nos",
    "wearing": "usando",
    "wears": "usa",
    "week": "semana",
    "weekend": "fim de semana",
    "welcome": "de nada",
    "well": "bem",
    "went": "saiu",
    "what": "o que",
    "when": "quando",
    "where": "onde",
    "white": "branco",
    "who": "quem",
    "why": "por que",
    "will": "vai",
    "with": "com",
    "won": "ganhei",
    "works": "trabalha",
    "worry": "preocupe",
    "would": "queria",
    "years": "anos",
    "yellow": "amarelo",
    "yesterday": "ontem",
    "you": "voce",
    "your": "seu",
}
